<?php

return [
    // Токен бота от @BotFather.
    'token' => env('TELEGRAM_TOKEN'),

    // Подлинность запроса проверяет App\Http\Middleware\VerifyTelegramWebhook
    // по секрету из TELEGRAM_WEBHOOK_SECRET. Встроенный safe_mode Nutgram
    // сверяет заголовок с md5(APP_KEY) и с нашим секретом конфликтует.
    'safe_mode' => false,

    // Extra or specific configurations
    'config' => [],

    // Обработчики бота лежат в routes/telegram.php.
    'routes' => true,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),

    // Set log channel
    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
];
